language: default
os: ubuntu
services:
    - docker
branches:
    only:
    - main
before_install:
    - pwd
script: 
    - echo installing kubectl
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - sudo mv ./kubectl /usr/local/bin/kubectl